spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/task-service/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080