spring:
  application:
    name: discovery-service
  cloud:
    discovery:
      client:
        registration:
          eureka:
            enabled: true
        service-url:
          defaultZone: http://localhost:8761/eureka/  
  eureka:
    instance:
      hostname: eureka-server 
    client:
      register-with-eureka: false  
      fetch-registry: false  

server:
  port: 8761
